// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe4lorFZh4HAKuA2O5NHxbRii7thH52FM',
    appId: '1:374438689243:web:144831c4b4ebdafd078ffe',
    messagingSenderId: '374438689243',
    projectId: 'pulsedatabese',
    authDomain: 'pulsedatabese.firebaseapp.com',
    databaseURL: 'https://pulsedatabese-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pulsedatabese.firebasestorage.app',
    measurementId: 'G-TPH9RRT8P9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj-040oqS5lJLVtKrb6-FPSnQJiTEe_WA',
    appId: '1:374438689243:android:7afbe39b77c8eb1e078ffe',
    messagingSenderId: '374438689243',
    projectId: 'pulsedatabese',
    databaseURL: 'https://pulsedatabese-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pulsedatabese.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi0BeDttwM9uPik02HFKtsKzG8VhDXK30',
    appId: '1:374438689243:ios:f9dca3498a87305e078ffe',
    messagingSenderId: '374438689243',
    projectId: 'pulsedatabese',
    databaseURL: 'https://pulsedatabese-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pulsedatabese.firebasestorage.app',
    iosBundleId: 'com.example.appPulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi0BeDttwM9uPik02HFKtsKzG8VhDXK30',
    appId: '1:374438689243:ios:f9dca3498a87305e078ffe',
    messagingSenderId: '374438689243',
    projectId: 'pulsedatabese',
    databaseURL: 'https://pulsedatabese-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pulsedatabese.firebasestorage.app',
    iosBundleId: 'com.example.appPulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe4lorFZh4HAKuA2O5NHxbRii7thH52FM',
    appId: '1:374438689243:web:a55ea441c40ce7bf078ffe',
    messagingSenderId: '374438689243',
    projectId: 'pulsedatabese',
    authDomain: 'pulsedatabese.firebaseapp.com',
    databaseURL: 'https://pulsedatabese-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pulsedatabese.firebasestorage.app',
    measurementId: 'G-QR05JFJ4YX',
  );
}
